version: 2
jobs:
  build:
    machine: #executors 
      image: ubuntu-2004:202010-01
     
    steps:
      - checkout
      - run: 
          name: Build image
          command: docker build . -t lavidoker/tpcicd2:latest
      - run:
          name: Test docker
          command: docker run -d --name=test -p 8080:8080 lavidoker/tpcicd2:latest && wget localhost:8080
      - run:
          name: Push image
          command: docker login -u "$DOCKER_USR" -p "$DOCKER_PASSWORD" && docker push lavidoker/tpcicd2:latest
          
          
     
