version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
      
    steps:
      - checkout
      - run: 
          name: Build image
          command: docker build . -t tpcicd
      - run:
          name: Test docker
          command: docker run -d --name=test -p 8080:8080 tpcicd && wget localhost:8080 
          
          
     
