version: 2
jobs:
  build:
    working_directory: /dockerapp1
    docker:
      - image: docker:17.05.0-ce-git
      
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          command: docker build . -t tpcicd
