version: 2
jobs:
  build:
    working_directory: /dockerapp1
    docker:
      - image: circleci/node:10
      
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          command: docker build . -t tpcicd
